build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    execute_command = "echo 'vagrant' | {{ .Vars }} sudo -SEH bash -x '{{ .Path }}'"
    script          = "scripts/ansible.sh"
  }

  provisioner "shell" {
    execute_command = "echo 'vagrant' | {{ .Vars }} sudo -SEH bash -x '{{ .Path }}'"
    script          = "scripts/setup.sh"
  }

  provisioner "ansible-local" {
    galaxy_file   = "../shared/requirements.yml"
    playbook_file = "../shared/main.yml"
  }

  provisioner "shell" {
    execute_command = "echo 'vagrant' | {{ .Vars }} sudo -SEH bash -x '{{ .Path }}'"
    script          = "scripts/cleanup.sh"
  }

  post-processors {
    post-processor "vagrant" {
      output = "builds/{{ .Provider }}-debian13-arm64.box"
    }
    post-processor "vagrant-registry" {
      architecture  = "${var.architecture}"
      box_tag       = "francois75/debian13-arm64"
      client_id     = "${var.hcp_client_id}"
      client_secret = "${var.hcp_client_secret}"
      version       = "${local.version}"
    }
  }
}
