source "virtualbox-iso" "autogenerated_1" {
  boot_command            = ["<enter><wait>", "e<down><down><down><end>", " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg ", "debian-installer=en_US.UTF-8 ", "auto ", "locale=en_US.UTF-8 ", "kbd-chooser/method=us ", "keyboard-configuration/xkb-keymap=us ", "netcfg/get_hostname={{ .Name }} ", "netcfg/get_domain=vagrantup.com ", "fb=false ", "debconf/frontend=noninteractive ", "console-setup/ask_detect=false ", "console-keymaps-at/keymap=us ", "grub-installer/bootdev=/dev/sda ", "<f10>"]
  boot_wait               = "5s"
  disk_size               = 81920
  guest_additions_path    = "VBoxGuestAdditions_{{ .Version }}.iso"
  guest_os_type           = "Debian12_arm64"
  hard_drive_interface    = "virtio"
  headless                = false
  http_directory          = "http"
  iso_checksum            = "sha512:3960cd54dcb3966476686003bb163f3385b26963cada7321d993e4e9fb8b1c19ba0a942e6365a329b48f148c68dc850f8e9e9d7200255e0e6b336f147dea751b"
  iso_interface           = "virtio"
  iso_urls                = ["debian-13.0.0-arm64-netinst.iso", "https://debian.ethz.ch/debian-cd/13.0.0/arm64/iso-cd/debian-13.0.0-arm64-netinst.iso"]
  shutdown_command        = "echo 'vagrant'|sudo -S shutdown -P now"
  ssh_password            = "vagrant"
  ssh_port                = 22
  ssh_username            = "vagrant"
  ssh_wait_timeout        = "1800s"
  vboxmanage              = [
    ["modifyvm", "{{ .Name }}", "--firmware", "efi"],
    ["modifyvm", "{{ .Name }}", "--ioapic", "on"],
    ["modifyvm", "{{ .Name }}", "--usb-xhci", "on"],
    ["modifyvm", "{{ .Name }}", "--vram", "21"],
    ["modifyvm", "{{ .Name }}", "--graphicscontroller", "vmsvga"],
    ["modifyvm", "{{ .Name }}", "--chipset", "armv8virtual"],
    ["modifyvm", "{{ .Name }}", "--memory", "2048"],
    ["modifyvm", "{{ .Name }}", "--cpus", "2"],
    ["modifyvm", "{{ .Name }}", "--boot1", "disk"],
    ["modifyvm", "{{ .Name }}", "--boot2", "dvd"],
    ["modifyvm", "{{ .Name }}", "--boot3", "none"],
    ["modifyvm", "{{ .Name }}", "--boot4", "none"],
    ["storagectl", "{{ .Name }}", "--name", "IDE Controller", "--remove"]
  ]
  virtualbox_version_file = ".vbox_version"
  vm_name                 = "packer-debian-13-arm64"
}
